### ISSUE TITLE
本地运行出错

### ISSUE THREAD

**Issue by cnblogsTim** [cnblogs/android-app#20]
![tim 20171212101529](https://user-images.githubusercontent.com/31572788/33864006-833ad22c-df25-11e7-9771-f40c22a95c47.png)

**Comment by cnblogsTim** [comment]
可能是没有配置`数字证书导致的这个问题`。推荐按照这篇配置一下：[http://reactnative.cn/docs/0.51/signed-apk-android.html#content](http://reactnative.cn/docs/0.51/signed-apk-android.html#content)

**Comment by sdfjshdjwenwen** [comment]
很好很好
