### ISSUE TITLE
关于项目在window下运行的问题

### ISSUE THREAD

**Issue by sdfjshdjwenwen** [cnblogs/android-app#22]
![image](https://user-images.githubusercontent.com/18532131/33943052-df9cfb52-e052-11e7-9d2e-92921f233635.png)

**Comment by cnblogsTim** [comment]
1.先删除本地项目
2.`git clone  https://github.com/cnblogs/android-app.git`
3.打开`src/config`文件下的`AppConfig`文件，配置申请的`ClientId`和`ClientSecret`,如果没有可以到[https://oauth.cnblogs.com](https://oauth.cnblogs.com)站点申请。
4.配置签名证书，可以参考这篇教程[打包APK](http://reactnative.cn/docs/0.51/signed-apk-android.html#content)
5.运行`react-native run-android`

**Comment by sdfjshdjwenwen** [comment]
假如上述方法操作行不通请把android的项目扔进android studio里面并执行以下操作
![image](https://user-images.githubusercontent.com/18532131/33998365-3e090ba2-e122-11e7-804b-9b93c46ce010.png)   点击
![image](https://user-images.githubusercontent.com/18532131/33998415-5fed9c24-e122-11e7-970a-1c149772db4f.png)make moudle ‘xxx’
